version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ['dependencies']
    commit-message:
      prefix: chore
      include: scope
    groups:
      electron:
        patterns:
          - 'electron*'

  - package-ecosystem: npm
    directory: '/services/license-server'
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ['dependencies', 'area: licensing']
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: '/services/admin-web'
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ['dependencies', 'area: operations center']
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    target-branch: main
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: ['dependencies', 'area: ci']
    commit-message:
      prefix: ci
