export {
  APP_ID,
  APP_NAME,
  APP_PROTOCOL_PREFIX,
  APP_SCHEME,
  APP_USER_MODEL_ID,
  BRAND,
  DB_FILENAME,
  DEFAULT_PROJECT_DIRECTORY,
} from '../shared/brand';

export const APP_ATTENTION_BADGE_COLOR = '#FF3B30';
