export const BRAND_UI_COPY = {
  zh: {
    brandPrimaryNavigation: '主要导航',
    brandNavGroupWork: '工作',
    brandNavGroupCapability: '能力',
    brandNavGroupConnection: '连接',
    brandNavGroupResources: '资源',
    brandWorkspaceNavigation: '工作空间',
    brandWorkspaceHint: '选择任务记录或专属助手查看内容',
    workHub: '工作中枢',
    defaultAgentDisplayName: '工作中枢',
    taskHistory: '任务记录',
    newChat: '新建任务',
    scheduledTasks: '自动任务',
    myAgents: '专属助手',
    assistantSettings: '助手设置',
    skills: '能力库',
    kits: '方案库',
    mcpServers: '连接中心',
    cowork: '工作中枢',
    coworkSettings: '工作中枢设置',
    coworkHistory: '任务记录',
    coworkPlaceholder: '描述你要完成的工作，或直接提出问题',
    workingDirectoryLabel: '工作目录',
    coworkHomeTagline: '从一个任务开始，调度你的能力与工具',
    commonWork: '常用工作',
    settingsNavigation: '设置导航',
    settingsGroupBasics: '基础设置',
    personalization: '个性化',
    personalizationProfileTitle: '个人资料',
    personalizationProfileDescription: '这些内容只显示在当前设备的账号入口中，不会修改远端账号或助手身份。',
    personalizationDisplayName: '显示姓名',
    personalizationDisplayNamePlaceholder: '留空时显示登录手机号',
    personalizationSignature: '个性签名',
    personalizationSignaturePlaceholder: '写一句介绍自己的话',
    personalizationAvatarTitle: '头像',
    personalizationAvatarDescription: '选择内置头像，或上传 PNG、JPG、WebP 图片（最大 10 MB）。',
    personalizationDefaultAvatar: '默认头像',
    personalizationPresetAvatar: '内置头像',
    personalizationUploadAvatar: '上传头像',
    personalizationImageFiles: '图片文件',
    personalizationUpload: '上传',
    personalizationUploading: '处理中',
    personalizationAvatarReadFailed: '无法读取头像图片',
    personalizationAvatarTooLarge: '头像图片不能超过 10 MB',
    personalizationAvatarUnsupported: '请选择 PNG、JPG 或 WebP 图片',
    accountDefaultName: '我的账号',
    accountLicenseRemaining: '卡密剩余',
    accountLicenseExpiresAt: '到期时间：',
    accountLicenseExpired: '卡密已到期',
    accountLicenseExpiryUnknown: '未提供到期时间',
    accountLoggingOut: '正在退出…',
    accountLogoutFailed: '退出登录失败，请稍后重试。',
    settingsGroupIntelligence: '智能能力',
    settingsGroupConnections: '连接与扩展',
    settingsGroupProduct: '产品',
    settingsCustomModel: '模型服务',
    coworkAgentEngine: '运行引擎',
    coworkMemoryTitle: '长期记忆',
    coworkMemoryTabDreaming: '记忆整理',
    browserWebAccessTab: '网页访问',
    imBot: '消息接入',
    emailTab: '邮件接入',
    pluginsTab: '扩展管理',
    shortcuts: '快捷操作',
    about: '关于逻栖工枢',
    logicnestLockedAgents: '专属助手',
    logicnestLockedSessions: '任务记录',
    logicnestLockedSkills: '能力库',
    logicnestLockedScheduledTasks: '自动任务',
    logicnestLockedMcp: '连接中心',
    logicnestLockedDescription: '账号已登录。激活会员后即可使用工作中枢、能力库、自动任务和连接中心。',
    engineStartingTitle: '运行引擎启动中',
    engineStartingTip2: '在「能力库」中启用文档、表格和演示能力，可直接生成办公文件',
    engineStartingTip3: '用「自动任务」在固定时间执行例行工作',
    engineStartingTip4: '通过「消息接入」连接常用沟通工具，随时发起任务',
    coworkOpenClawInstall: '启动运行引擎',
    coworkOpenClawRetryInstall: '重试启动',
    coworkOpenClawStart: '启动运行引擎',
    coworkOpenClawGoToSettingsInstall: '查看运行引擎设置',
    coworkOpenClawRestartGateway: '重启运行引擎',
    coworkMemoryEnabledHint: '启用后，工作中枢会索引记忆文件，在后续任务中检索长期信息。',
    coworkMemoryLegacyNotice: '长期记忆仅对支持该能力的运行引擎生效。',
    pluginsDesc: '安装和管理扩展，为工作中枢补充连接与自动化能力。',
    syncSkillsFromOpenClaw: '从运行环境同步',
    skillsSyncFound: '检测到 {count} 个可从运行环境同步的能力：',
    skillsSyncLater: '如果现在不同步，后续可在「添加」菜单中再次同步。',
    pluginsSyncDesc: '发现运行环境中的扩展并同步到管理列表。',
    pluginsSyncFound: '检测到 {count} 个可同步的扩展：',
    pluginsSyncLater: '如果现在不同步，后续可在「安装扩展」中再次同步。',
    browserWebAccessDescription: '管理网页打开方式、独立访问环境和站点规则。',
    browserProfileManagedDescription: '使用专用网页访问环境，隔离日常浏览数据。',
    email: '邮件接入',
    shareCardBrandTagline: '逻栖工枢 · 智能工作中枢',
    shareCardBrandByline: '把任务、能力与连接归拢到一个工作中枢',
  },
  en: {
    brandPrimaryNavigation: 'Primary navigation',
    brandNavGroupWork: 'Work',
    brandNavGroupCapability: 'Capabilities',
    brandNavGroupConnection: 'Connections',
    brandNavGroupResources: 'Resources',
    brandWorkspaceNavigation: 'Workspace',
    brandWorkspaceHint: 'Choose Task History or Personal Assistants to view its contents',
    workHub: 'Work Hub',
    defaultAgentDisplayName: 'Work Hub',
    taskHistory: 'Task History',
    newChat: 'New Task',
    scheduledTasks: 'Automations',
    myAgents: 'Personal Assistants',
    assistantSettings: 'Assistant settings',
    skills: 'Capability Library',
    kits: 'Solution Library',
    mcpServers: 'Connection Center',
    cowork: 'Work Hub',
    coworkSettings: 'Work Hub Settings',
    coworkHistory: 'Task History',
    coworkPlaceholder: 'Describe the work you want to complete, or ask a question',
    workingDirectoryLabel: 'Working directory',
    coworkHomeTagline: 'Start with one task, then coordinate your capabilities and tools',
    commonWork: 'Common Work',
    settingsNavigation: 'Settings navigation',
    settingsGroupBasics: 'Basics',
    personalization: 'Personalization',
    personalizationProfileTitle: 'Profile',
    personalizationProfileDescription: 'These details appear only in the account area on this device. They do not change your remote account or assistant identity.',
    personalizationDisplayName: 'Display name',
    personalizationDisplayNamePlaceholder: 'Leave blank to show the signed-in phone number',
    personalizationSignature: 'Signature',
    personalizationSignaturePlaceholder: 'Write a short line about yourself',
    personalizationAvatarTitle: 'Avatar',
    personalizationAvatarDescription: 'Choose a built-in avatar or upload a PNG, JPG, or WebP image (up to 10 MB).',
    personalizationDefaultAvatar: 'Default avatar',
    personalizationPresetAvatar: 'Built-in avatar',
    personalizationUploadAvatar: 'Upload avatar',
    personalizationImageFiles: 'Image files',
    personalizationUpload: 'Upload',
    personalizationUploading: 'Processing',
    personalizationAvatarReadFailed: 'Unable to read the avatar image',
    personalizationAvatarTooLarge: 'Avatar images must be no larger than 10 MB',
    personalizationAvatarUnsupported: 'Choose a PNG, JPG, or WebP image',
    accountDefaultName: 'My account',
    accountLicenseRemaining: 'License remaining',
    accountLicenseExpiresAt: 'Expires:',
    accountLicenseExpired: 'License expired',
    accountLicenseExpiryUnknown: 'Expiration time unavailable',
    accountLoggingOut: 'Signing out…',
    accountLogoutFailed: 'Could not sign out. Try again later.',
    settingsGroupIntelligence: 'Intelligence',
    settingsGroupConnections: 'Connections & Extensions',
    settingsGroupProduct: 'Product',
    settingsCustomModel: 'Model Services',
    coworkAgentEngine: 'Runtime Engine',
    coworkMemoryTitle: 'Long-term Memory',
    coworkMemoryTabDreaming: 'Memory Organization',
    browserWebAccessTab: 'Web Access',
    imBot: 'Messaging Access',
    emailTab: 'Email Access',
    pluginsTab: 'Extension Management',
    shortcuts: 'Quick Actions',
    about: 'About LogicNest WorkHub',
    logicnestLockedAgents: 'Personal Assistants',
    logicnestLockedSessions: 'Task History',
    logicnestLockedSkills: 'Capability Library',
    logicnestLockedScheduledTasks: 'Automations',
    logicnestLockedMcp: 'Connection Center',
    logicnestLockedDescription: 'Your account is signed in. Activate membership to use the Work Hub, capability library, automations, and connection center.',
    engineStartingTitle: 'Runtime Engine Starting',
    engineStartingTip2: 'Enable document, spreadsheet, and presentation tools in the Capability Library to create office files directly',
    engineStartingTip3: 'Use Automations to run recurring work on a schedule',
    engineStartingTip4: 'Connect communication tools through Messaging Access and start tasks from anywhere',
    coworkOpenClawInstall: 'Start Runtime Engine',
    coworkOpenClawRetryInstall: 'Retry Startup',
    coworkOpenClawStart: 'Start Runtime Engine',
    coworkOpenClawGoToSettingsInstall: 'View Runtime Engine Settings',
    coworkOpenClawRestartGateway: 'Restart Runtime Engine',
    coworkMemoryEnabledHint: 'When enabled, the Work Hub indexes memory files and retrieves long-term information for future tasks.',
    coworkMemoryLegacyNotice: 'Long-term memory applies only to runtime engines that support it.',
    pluginsDesc: 'Install and manage extensions that add connections and automation to the Work Hub.',
    syncSkillsFromOpenClaw: 'Sync from Runtime',
    skillsSyncFound: 'Found {count} capabilities available to sync from the runtime:',
    skillsSyncLater: 'You can sync again later from the Add menu.',
    pluginsSyncDesc: 'Discover runtime extensions and sync them into this list.',
    pluginsSyncFound: 'Found {count} extensions available to sync:',
    pluginsSyncLater: 'You can sync again later from Install Extension.',
    browserWebAccessDescription: 'Manage page opening, the dedicated access environment, and site rules.',
    browserProfileManagedDescription: 'Use a dedicated web environment isolated from everyday browsing data.',
    email: 'Email Access',
    shareCardBrandTagline: 'LogicNest WorkHub · Intelligent Work Hub',
    shareCardBrandByline: 'Bring tasks, capabilities, and connections into one work hub',
  },
} as const;
