export const MEETING_ROOM_COPY = {
  zh: {
    meetingRooms: '会议室',
    meetingRoomsTitle: '会议室',
    meetingRoomsSubtitle: '让多个专属助手围绕同一议题进行有序讨论',
    meetingNew: '创建会议',
    meetingEmpty: '还没有会议',
    meetingEmptyHint: '选择 2～5 名参与者，开始一次多 Agent 讨论。',
    meetingTitle: '标题',
    meetingTitlePlaceholder: '留空时将从议题自动生成',
    meetingTopic: '议题',
    meetingTopicPlaceholder: '说明问题、目标、约束和期望产出',
    meetingMode: '讨论模式',
    meetingModeSequential: '顺序讨论',
    meetingModeExpertPanel: '专家 Panel',
    meetingModeBrainstorm: '头脑风暴',
    meetingRounds: '轮数',
    meetingParticipants: '参与者',
    meetingParticipantHint: '选择 2～5 名已启用助手；可拖动或使用键盘调整发言顺序。',
    meetingRoleNote: '本次会议角色备注',
    meetingRoleNotePlaceholder: '追加到原身份后，不会覆盖原身份',
    meetingVisionYes: '支持视觉',
    meetingVisionNo: '不支持视觉',
    meetingAttachments: '图片附件',
    meetingAddImages: '添加图片',
    meetingCreate: '保存草稿',
    meetingCancel: '取消',
    meetingStart: '开始',
    meetingPause: '暂停',
    meetingResume: '恢复',
    meetingStop: '停止',
    meetingDelete: '删除',
    meetingRetryHost: '重试主持人',
    meetingAppendRound: '追加一轮',
    meetingSupplement: '补充意见',
    meetingSupplementPlaceholder: '说明需要继续讨论的新信息或问题',
    meetingExportMarkdown: '导出 Markdown',
    meetingExportHtml: '导出 HTML',
    meetingBack: '返回会议列表',
    meetingHost: '主持人',
    meetingCurrentSpeaker: '当前发言者',
    meetingRoundProgress: '第 {current} / {total} 轮',
    meetingFinalSummary: '最终总结',
    meetingDiscussion: '讨论记录',
    meetingTokens: 'Token：输入 {input} / 输出 {output}',
    meetingNoVisionConfirm: '主持人和所有参与者都不支持视觉输入。会议仍可继续，但只能依据文字议题，是否继续？',
    meetingContinue: '继续会议',
    meetingDeleteConfirm: '确认删除该会议及其隐藏会话和附件？此操作无法撤销。',
    meetingStopConfirm: '确认停止会议？停止后不能恢复。',
    meetingError: '会议操作失败',
    meetingStatusDraft: '草稿',
    meetingStatusRunning: '运行中',
    meetingStatusPaused: '已暂停',
    meetingStatusCompleted: '已完成',
    meetingStatusStopped: '已停止',
    meetingTurnPending: '等待中',
    meetingTurnRunning: '发言中',
    meetingTurnCompleted: '已完成',
    meetingTurnInterrupted: '已中断',
    meetingTurnFailed: '失败',
    meetingTurnSkipped: '已跳过',
    meetingLoading: '正在加载会议…',
    meetingSaving: '正在保存…',
    meetingNoAgents: '至少需要 2 名已启用助手。',
    meetingRunningIndicator: '有会议正在运行',
    meetingInvalidImage: '图片格式无效或超过现有大小限制。',
  },
  en: {
    meetingRooms: 'Meeting Rooms',
    meetingRoomsTitle: 'Meeting Rooms',
    meetingRoomsSubtitle: 'Bring multiple assistants into a focused, structured discussion',
    meetingNew: 'New Meeting',
    meetingEmpty: 'No meetings yet',
    meetingEmptyHint: 'Choose 2–5 participants and start a multi-agent discussion.',
    meetingTitle: 'Title',
    meetingTitlePlaceholder: 'Leave blank to generate it from the topic',
    meetingTopic: 'Topic',
    meetingTopicPlaceholder: 'Describe the problem, goal, constraints, and expected output',
    meetingMode: 'Discussion mode',
    meetingModeSequential: 'Sequential',
    meetingModeExpertPanel: 'Expert Panel',
    meetingModeBrainstorm: 'Brainstorm',
    meetingRounds: 'Rounds',
    meetingParticipants: 'Participants',
    meetingParticipantHint: 'Choose 2–5 enabled assistants. Drag or use the keyboard to change speaking order.',
    meetingRoleNote: 'Meeting role note',
    meetingRoleNotePlaceholder: 'Appended to the original identity; it never replaces it',
    meetingVisionYes: 'Vision',
    meetingVisionNo: 'No vision',
    meetingAttachments: 'Image attachments',
    meetingAddImages: 'Add images',
    meetingCreate: 'Save Draft',
    meetingCancel: 'Cancel',
    meetingStart: 'Start',
    meetingPause: 'Pause',
    meetingResume: 'Resume',
    meetingStop: 'Stop',
    meetingDelete: 'Delete',
    meetingRetryHost: 'Retry Host',
    meetingAppendRound: 'Append Round',
    meetingSupplement: 'Supplement',
    meetingSupplementPlaceholder: 'Add new information or questions for the next round',
    meetingExportMarkdown: 'Export Markdown',
    meetingExportHtml: 'Export HTML',
    meetingBack: 'Back to meetings',
    meetingHost: 'Host',
    meetingCurrentSpeaker: 'Current speaker',
    meetingRoundProgress: 'Round {current} / {total}',
    meetingFinalSummary: 'Final Summary',
    meetingDiscussion: 'Discussion',
    meetingTokens: 'Tokens: input {input} / output {output}',
    meetingNoVisionConfirm: 'The host and all participants lack vision input. The meeting can continue using text only. Continue?',
    meetingContinue: 'Continue Meeting',
    meetingDeleteConfirm: 'Delete this meeting, its hidden sessions, and attachments? This cannot be undone.',
    meetingStopConfirm: 'Stop this meeting? A stopped meeting cannot be resumed.',
    meetingError: 'Meeting operation failed',
    meetingStatusDraft: 'Draft',
    meetingStatusRunning: 'Running',
    meetingStatusPaused: 'Paused',
    meetingStatusCompleted: 'Completed',
    meetingStatusStopped: 'Stopped',
    meetingTurnPending: 'Pending',
    meetingTurnRunning: 'Speaking',
    meetingTurnCompleted: 'Completed',
    meetingTurnInterrupted: 'Interrupted',
    meetingTurnFailed: 'Failed',
    meetingTurnSkipped: 'Skipped',
    meetingLoading: 'Loading meetings…',
    meetingSaving: 'Saving…',
    meetingNoAgents: 'At least two enabled assistants are required.',
    meetingRunningIndicator: 'A meeting is running',
    meetingInvalidImage: 'The image format is invalid or exceeds the existing size limit.',
  },
} as const;
