export const SETTINGS_CENTER_COPY = {
  zh: {
    settingsCenterTitle: '设置中心',
    settingsCenterHome: '设置首页',
    settingsCenterBack: '返回设置首页',
    settingsCenterSearchPlaceholder: '搜索设置',
    settingsCenterSearchResults: '搜索结果',
    settingsCenterSearchNoResults: '没有找到相关设置',
    settingsCenterHomeTitle: '逻栖工枢设置中心',
    settingsCenterHomeDescription: '按工作场景查找设置。每项配置仍保留原有保存、即时生效和安全校验方式。',
    settingsCenterItemUnit: '项',
    settingsCenterEnterModule: '进入模块',
    settingsCenterSaveChanges: '保存更改',
    settingsCenterCancelChanges: '取消并关闭',
    settingsModulePersonalInterface: '个人与界面',
    settingsModulePersonalInterfaceDescription: '管理应用行为、个人资料、视觉主题与快捷操作。',
    settingsModuleIntelligentCore: '智能内核',
    settingsModuleIntelligentCoreDescription: '配置模型服务和本地运行引擎。',
    settingsModuleMemorySystem: '记忆系统',
    settingsModuleMemorySystemDescription: '控制长期记忆、索引和记忆整理。',
    settingsModuleConnectionChannels: '连接通道',
    settingsModuleConnectionChannelsDescription: '管理网页访问、消息与邮件接入。',
    settingsModuleExtensions: '扩展组件',
    settingsModuleExtensionsDescription: '安装、筛选并管理第三方扩展。',
    settingsModuleSystemSupport: '系统与支持',
    settingsModuleSystemSupportDescription: '查看产品信息、使用指南、安全说明并导出日志。',
    settingsTabGeneralDescription: '语言、启动、通知、自动任务、数据与隐私。',
    settingsTabGeneralKeywords: '应用行为 通知 自动任务 备份 隐私 代理 睡眠',
    settingsTabPersonalizationDescription: '当前账号资料和此设备上的本地头像。',
    settingsTabPersonalizationKeywords: '账号 昵称 签名 头像 上传',
    settingsTabAppearanceDescription: '浅色、深色、跟随系统、主题、皮肤和字体。',
    settingsTabAppearanceKeywords: '主题 配色 皮肤 字号 字体 明暗',
    settingsTabShortcutsDescription: '查看和编辑全局命令快捷键。',
    settingsTabShortcutsKeywords: '键盘 键帽 命令 热键 快捷键',
    settingsTabModelDescription: '服务商、连接测试、模型管理及安全导入导出。',
    settingsTabModelKeywords: '服务商 API 密钥 加密 导入 导出 连接测试 自定义模型',
    settingsTabRuntimeDescription: '运行状态、启动操作、安装修复与高级配置。',
    settingsTabRuntimeKeywords: '运行状态 网关 启动 重启 安装 修复 高级配置',
    settingsTabMemoryDescription: '长期记忆开关、索引状态、统计与管理。',
    settingsTabMemoryKeywords: '长期记忆 索引 检索 向量 统计 管理',
    settingsTabDreamingDescription: '按既有策略整理和沉淀记忆。',
    settingsTabDreamingKeywords: '记忆整理 频率 自动整理 沉淀',
    settingsTabBrowserDescription: '默认安全策略、局域网风险和站点规则。',
    settingsTabBrowserKeywords: '网页 浏览器 SSRF 局域网 安全 站点规则',
    settingsTabMessagingDescription: '查看渠道状态并配置消息接入。',
    settingsTabMessagingKeywords: '消息 渠道 机器人 接入 状态',
    settingsTabEmailDescription: '查看邮件渠道状态并配置收发能力。',
    settingsTabEmailKeywords: '邮件 邮箱 IMAP SMTP 渠道 接入',
    settingsTabPluginsDescription: '筛选、安装和管理运行环境扩展。',
    settingsTabPluginsKeywords: '扩展 插件 安装 启用 第三方',
    settingsTabAboutDescription: '版本、指南、安全审计、日志和版权信息。',
    settingsTabAboutKeywords: '关于 版本 指南 激活 安全 审计 日志 版权',
    settingsSectionApplicationBehavior: '应用行为',
    settingsSectionApplicationBehaviorDescription: '控制语言、开机启动和设备工作方式。',
    settingsSectionNotifications: '通知',
    settingsSectionNotificationsDescription: '决定任务、权限和提问何时提醒你。',
    settingsSectionAutomations: '自动任务',
    settingsSectionAutomationsDescription: '配置后台自动任务可使用的并发资源。',
    settingsSectionDataPrivacy: '数据与隐私',
    settingsSectionDataPrivacyDescription: '管理本地备份、代理和隐私相关选项。',
    settingsAppearanceModeTitle: '明暗模式',
    settingsAppearanceModeDescription: '选择固定明暗模式，或跟随 Windows 系统设置。',
    settingsAppearanceThemeTitle: '主题色板',
    settingsAppearanceThemeDescription: '色板直接取自主题的真实界面颜色，不模拟应用窗口。',
    settingsAppearanceTypographyTitle: '文字尺寸',
    settingsAppearanceTypographyDescription: '分别调整界面文字和代码区域字号。',
    settingsShortcutsCommandColumn: '功能与说明',
    settingsShortcutsKeyColumn: '按键与编辑',
    settingsAboutProductInfo: '产品信息',
    settingsAboutProductInfoDescription: '当前安装版本与由企业配置管理的更新状态。',
    settingsAboutSupportResources: '使用与支持',
    settingsAboutSupportResourcesDescription: '查看本地指南、安全审计说明，或导出诊断日志。',
    settingsAboutCopyright: '版权信息',
    settingsExtensionsFilterPlaceholder: '筛选扩展名称、说明或来源',
    settingsExtensionsNoFilterResults: '没有符合筛选条件的扩展',
  },
  en: {
    settingsCenterTitle: 'Settings Center',
    settingsCenterHome: 'Settings home',
    settingsCenterBack: 'Back to settings home',
    settingsCenterSearchPlaceholder: 'Search settings',
    settingsCenterSearchResults: 'Search results',
    settingsCenterSearchNoResults: 'No matching settings',
    settingsCenterHomeTitle: 'LogicNest WorkHub Settings Center',
    settingsCenterHomeDescription: 'Find settings by work area. Existing save, immediate-apply, and safety behavior remains unchanged.',
    settingsCenterItemUnit: 'items',
    settingsCenterEnterModule: 'Open module',
    settingsCenterSaveChanges: 'Save changes',
    settingsCenterCancelChanges: 'Cancel and close',
    settingsModulePersonalInterface: 'Personal & Interface',
    settingsModulePersonalInterfaceDescription: 'Manage app behavior, your profile, visual themes, and quick actions.',
    settingsModuleIntelligentCore: 'Intelligence Core',
    settingsModuleIntelligentCoreDescription: 'Configure model services and the local runtime engine.',
    settingsModuleMemorySystem: 'Memory System',
    settingsModuleMemorySystemDescription: 'Control long-term memory, indexing, and memory organization.',
    settingsModuleConnectionChannels: 'Connection Channels',
    settingsModuleConnectionChannelsDescription: 'Manage web access, messaging, and email connections.',
    settingsModuleExtensions: 'Extensions',
    settingsModuleExtensionsDescription: 'Install, filter, and manage third-party extensions.',
    settingsModuleSystemSupport: 'System & Support',
    settingsModuleSystemSupportDescription: 'View product details, guides, security notes, and exported logs.',
    settingsTabGeneralDescription: 'Language, startup, notifications, automations, data, and privacy.',
    settingsTabGeneralKeywords: 'app behavior notifications automations backup privacy proxy sleep',
    settingsTabPersonalizationDescription: 'Current account details and a local avatar on this device.',
    settingsTabPersonalizationKeywords: 'account display name signature avatar upload',
    settingsTabAppearanceDescription: 'Light, dark, system, themes, and typography.',
    settingsTabAppearanceKeywords: 'theme palette font size light dark',
    settingsTabShortcutsDescription: 'Review and edit global command shortcuts.',
    settingsTabShortcutsKeywords: 'keyboard keycap command hotkey shortcut',
    settingsTabModelDescription: 'Providers, connection tests, models, and secure import or export.',
    settingsTabModelKeywords: 'provider API key encryption import export connection test custom model',
    settingsTabRuntimeDescription: 'Runtime status, primary actions, installation, repair, and advanced configuration.',
    settingsTabRuntimeKeywords: 'runtime status gateway start restart install repair advanced',
    settingsTabMemoryDescription: 'Long-term memory, index status, statistics, and management.',
    settingsTabMemoryKeywords: 'long-term memory index retrieval vector statistics management',
    settingsTabDreamingDescription: 'Organize and consolidate memory with existing policies.',
    settingsTabDreamingKeywords: 'memory organization frequency automatic consolidation',
    settingsTabBrowserDescription: 'Default security policy, local-network risk, and site rules.',
    settingsTabBrowserKeywords: 'web browser SSRF local network security site rules',
    settingsTabMessagingDescription: 'Review channel status before configuring messaging access.',
    settingsTabMessagingKeywords: 'messaging channel bot access status',
    settingsTabEmailDescription: 'Review email channel status before configuring send and receive access.',
    settingsTabEmailKeywords: 'email IMAP SMTP channel access',
    settingsTabPluginsDescription: 'Filter, install, and manage runtime extensions.',
    settingsTabPluginsKeywords: 'extension plugin install enable third party',
    settingsTabAboutDescription: 'Version, guides, security audit, logs, and copyright.',
    settingsTabAboutKeywords: 'about version guide activation security audit logs copyright',
    settingsSectionApplicationBehavior: 'App behavior',
    settingsSectionApplicationBehaviorDescription: 'Control language, startup, and how this device works.',
    settingsSectionNotifications: 'Notifications',
    settingsSectionNotificationsDescription: 'Choose when tasks, permissions, and questions notify you.',
    settingsSectionAutomations: 'Automations',
    settingsSectionAutomationsDescription: 'Configure the concurrent resources available to background automations.',
    settingsSectionDataPrivacy: 'Data & privacy',
    settingsSectionDataPrivacyDescription: 'Manage local backups, proxy behavior, and privacy options.',
    settingsAppearanceModeTitle: 'Color mode',
    settingsAppearanceModeDescription: 'Choose a fixed mode or follow the Windows system setting.',
    settingsAppearanceThemeTitle: 'Theme palettes',
    settingsAppearanceThemeDescription: 'Palettes use actual interface colors from each theme without simulating an app window.',
    settingsAppearanceTypographyTitle: 'Type sizes',
    settingsAppearanceTypographyDescription: 'Adjust interface and code sizes independently.',
    settingsShortcutsCommandColumn: 'Command and description',
    settingsShortcutsKeyColumn: 'Keys and edit',
    settingsAboutProductInfo: 'Product information',
    settingsAboutProductInfoDescription: 'Installed version and update state managed by enterprise configuration.',
    settingsAboutSupportResources: 'Usage & support',
    settingsAboutSupportResourcesDescription: 'Open local guides and security audit notes, or export diagnostic logs.',
    settingsAboutCopyright: 'Copyright',
    settingsExtensionsFilterPlaceholder: 'Filter by extension name, description, or source',
    settingsExtensionsNoFilterResults: 'No extensions match this filter',
  },
} as const;
